import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getThemeConfig } from "@/theme-config";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const themeConfiguration = await getThemeConfig();
  
  // Convert CSS variables object to CSS string
  const cssVariablesString = Object.entries(themeConfiguration)
    .map(([key, value]) => `${key}: ${value};`)
    .join('\n    ');

  return (
    <html lang="en">
      <head>
        <style>
          {`:root {
    ${cssVariablesString}
  }`}
        </style>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        {children}
      </body>
    </html>
  );
}
